version: '2'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile-PHP
    volumes:
      - "../../:/var/www/html/"
    privileged: true
    network_mode: host
    command: sleep 10000000


